### ISSUE TITLE
Tasks für Milestone V1

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-contact#19]
- [x] Import FAU-Person Data (Switch CPT)
- [ ] Test import FAU-Person Data => images
- [x] Import UnivIS Data
- [x] Import UnivIS Data & overwrite local Data
- [x] use Location-Data
- [x] Import UnivIS Data, overwrite local Data, use Location-Data, add Fields
- [x] all Formats (shortcode) using Template (card.html, compact.html, default.html, list.html, name.html, page.html, plain.html, shortlist.html, sidebar.html, table.html)
- [x] all Formats with Accordions (parameter)
- [ ] hide/show mit allen Formaten testen- [x] single/single-contact-fau-theme single/single-contact single/single-location-fau-theme single/single-location
- [ ] Sprechstunden
- [ ] error.html
- [ ] cron
- [x] sync on update
- [x] cache
- [ ] list & clear cache  
- [ ] Import FAU-Person Settings
- [x] translate FAU-Person Shortcodes kontakt, person, kontaktliste and persons into `[contact ...]`
- [ ] translate FAU-Person Shortcode standort into `[location ...]`
- [ ] Test all FAU-Person Shortcodes

**Comment by xwolfde** [comment]
wir gehen das anders an. 
Daher erstmal wontfix close
